const smartphoneModels = [
  {
    deviceOs: "ios",
    name: "Apple",
    manufacturer: "Apple",
    priority: 1,
    models: [
      {
        name: "iPhone 12 mini",
        memories: ["64GB", "128GB", "256GB"],
        priority: 1,
      },
      { name: "iPhone 12", memories: ["64GB", "128GB", "256GB"], priority: 2 },
      {
        name: "iPhone 12 Pro",
        memories: ["128GB", "256GB", "512GB"],
        priority: 3,
      },
      {
        name: "iPhone 12 Pro Max",
        memories: ["128GB", "256GB", "512GB"],
        priority: 4,
      },
      {
        name: "iPhone SE 2020",
        memories: ["64GB", "128GB", "256GB"],
        priority: 5,
      },
      { name: "iPhone 11", memories: ["256GB", "128GB", "64GB"], priority: 6 },
      {
        name: "iPhone 11 Pro",
        memories: ["256GB", "512GB", "64GB"],
        priority: 7,
      },
      {
        name: "iPhone 11 Pro Max",
        memories: ["512GB", "256GB", "64GB"],
        priority: 8,
      },
      { name: "iPhone XS", memories: ["512GB", "256GB", "64GB"], priority: 9 },
      {
        name: "iPhone XS Max",
        memories: ["512GB", "256GB", "64GB"],
        priority: 10,
      },
      { name: "iPhone XR", memories: ["64GB", "128GB", "256GB"], priority: 11 },
      { name: "iPhone X", memories: ["64GB", "256GB"], priority: 12 },
      { name: "iPhone 8", memories: ["128GB", "256GB", "64GB"], priority: 13 },
      {
        name: "iPhone 8 Plus",
        memories: ["128GB", "256GB", "64GB"],
        priority: 14,
      },
      { name: "iPhone 7", memories: ["32GB", "256GB", "128GB"], priority: 15 },
      {
        name: "iPhone 7 Plus",
        memories: ["128GB", "32GB", "256GB"],
        priority: 16,
      },
      {
        name: "iPhone 6S",
        memories: ["32GB", "128GB", "16GB", "64GB"],
        priority: 17,
      },
      {
        name: "iPhone 6S Plus",
        memories: ["32GB", "16GB", "64GB", "128GB"],
        priority: 18,
      },
    ],
  },
  {
    deviceOs: "android",
    name: "Samsung Galaxy S",
    manufacturer: "Samsung",
    priority: 2,
    models: [
      { name: "Galaxy S20 FE", memories: ["128GB", "256GB"], priority: 1 },
      { name: "Galaxy S20 Ultra", memories: ["512GB", "128GB"], priority: 2 },
      { name: "Galaxy S20 Plus", memories: ["128GB"], priority: 3 },
      { name: "Galaxy S20", memories: ["128GB"], priority: 4 },
      { name: "Galaxy S10 Lite", memories: ["128GB"], priority: 5 },
      { name: "Galaxy S10e", memories: ["128GB"], priority: 6 },
      {
        name: "Galaxy S10 Plus",
        memories: ["512GB", "1024GB", "128GB"],
        priority: 7,
      },
      { name: "Galaxy S10", memories: ["512GB", "128GB"], priority: 8 },
      { name: "Galaxy S9", memories: ["128GB", "64GB"], priority: 9 },
      { name: "Galaxy S8 Plus", memories: ["128GB", "64GB"], priority: 10 },
      { name: "Galaxy S8", memories: ["64GB"], priority: 11 },
      { name: "Galaxy S9 Plus", memories: ["64GB", "128GB"], priority: 12 },
    ],
  },
  {
    deviceOs: "android",
    name: "Samsung Galaxy Note",
    manufacturer: "Samsung",
    priority: 3,
    models: [
      {
        name: "Galaxy Note 20 Ultra",
        memories: ["256GB", "512GB"],
        priority: 1,
      },
      { name: "Galaxy Note 20", memories: ["256GB"], priority: 2 },
      { name: "Galaxy Note 10 Lite", memories: ["128GB"], priority: 3 },
      {
        name: "Galaxy Note 10 Plus",
        memories: ["512GB", "256GB"],
        priority: 4,
      },
      { name: "Galaxy Note 10", memories: ["256GB"], priority: 5 },
      { name: "Galaxy Note 9", memories: ["128GB", "512GB"], priority: 6 },
      { name: "Galaxy Note 8", memories: ["64GB", "128GB"], priority: 7 },
    ],
  },
  {
    deviceOs: "android",
    name: "Samsung Galaxy A",
    manufacturer: "Samsung",
    priority: 4,
    models: [
      { name: "Galaxy A31", memories: ["128GB"], priority: 1 },
      { name: "Galaxy A21s", memories: ["64GB"], priority: 2 },
      { name: "Galaxy A11", memories: ["64GB"], priority: 3 },
      { name: "Galaxy A71", memories: ["128GB"], priority: 4 },
      { name: "Galaxy A30S", memories: ["64GB"], priority: 6 },
      { name: "Galaxy A20S", memories: ["32GB"], priority: 7 },
      { name: "Galaxy A10S", memories: ["32GB"], priority: 8 },
      { name: "Galaxy A6 Plus", memories: ["64GB"], priority: 9 },
      { name: "Galaxy A7", memories: ["128GB", "64GB"], priority: 10 },
      { name: "Galaxy A8 Plus", memories: ["64GB"], priority: 11 },
      { name: "Galaxy A8", memories: ["64GB"], priority: 12 },
      { name: "Galaxy A9", memories: ["128GB"], priority: 13 },
      { name: "Galaxy A80", memories: ["128GB"], priority: 14 },
      { name: "Galaxy A70", memories: ["128GB"], priority: 15 },
      { name: "Galaxy A50", memories: ["64GB", "128GB"], priority: 16 },
      { name: "Galaxy A30", memories: ["64GB"], priority: 17 },
      { name: "Galaxy A20", memories: ["32GB"], priority: 18 },
      { name: "Galaxy A10", memories: ["32GB"], priority: 19 },
    ],
  },
  {
    deviceOs: "android",
    name: "Samsung Galaxy J",
    manufacturer: "Samsung",
    priority: 5,
    models: [
      { name: "Galaxy J8", memories: ["64GB"], priority: 1 },
      { name: "Galaxy J7 Neo", memories: ["16GB"], priority: 2 },
      { name: "Galaxy J7 Duo", memories: ["32GB"], priority: 3 },
      { name: "Galaxy J6 Plus", memories: ["32GB"], priority: 4 },
      { name: "Galaxy J6", memories: ["32GB", "64GB"], priority: 5 },
      { name: "Galaxy J4 Plus", memories: ["32GB"], priority: 6 },
      { name: "Galaxy J4", memories: ["16GB", "32GB"], priority: 7 },
      { name: "Galaxy J4 Core", memories: ["16GB"], priority: 8 },
      { name: "Galaxy J7 Prime 2", memories: ["32GB"], priority: 9 },
      { name: "Galaxy J7 Prime", memories: ["32GB"], priority: 10 },
      { name: "Galaxy J5 Prime", memories: ["32GB"], priority: 11 },
      { name: "Galaxy J2 Prime", memories: ["16GB", "8GB"], priority: 12 },
      { name: "Galaxy J7 Pro", memories: ["64GB"], priority: 13 },
      { name: "Galaxy J5 Pro", memories: ["32GB"], priority: 14 },
      { name: "Galaxy J2 Pro (2018)", memories: ["16GB"], priority: 15 },
    ],
  },
  {
    deviceOs: "android",
    name: "Xiaomi Mi",
    manufacturer: "Xiaomi",
    priority: 6,
    models: [
      { name: "Mi 10 Pro", memories: ["256GB"], priority: 1 },
      { name: "Mi 10", memories: ["128GB"], priority: 2 },
      { name: "Mi Note 10 Pro", memories: ["256GB"], priority: 3 },
      { name: "Mi Note 10", memories: ["128GB"], priority: 4 },
      { name: "Mi Note 10 Lite", memories: ["128GB"], priority: 5 },
      { name: "Mi 9", memories: ["64GB", "128GB"], priority: 6 },
      { name: "Mi 9T", memories: ["64GB", "128GB"], priority: 7 },
      { name: "Mi 9 SE", memories: ["64GB", "128GB"], priority: 8 },
      { name: "Mi 9 Lite", memories: ["64GB", "128GB"], priority: 9 },
      { name: "Mi 8", memories: ["64GB"], priority: 10 },
      { name: "Mi 8 Lite", memories: ["64GB"], priority: 11 },
      { name: "Mi A3", memories: ["64GB", "128GB"], priority: 12 },
    ],
  },
  {
    deviceOs: "android",
    name: "Xiaomi POCO",
    manufacturer: "Xiaomi",
    priority: 7,
    models: [
      { name: "POCO F2 Pro", memories: ["128GB"], priority: 1 },
      { name: "POCOPHONE F1", memories: ["64GB", "128GB"], priority: 2 },
      { name: "POCO X3 NFC", memories: ["128GB"], priority: 3 },
    ],
  },
  {
    deviceOs: "android",
    name: "Xiaomi Redmi",
    manufacturer: "Xiaomi",
    priority: 8,
    models: [
      { name: "Redmi Note 9 Pro", memories: ["64GB", "128GB"], priority: 1 },
      { name: "Redmi Note 9S", memories: ["64GB", "128GB"], priority: 2 },
      { name: "Redmi Note 9", memories: ["64GB", "128GB"], priority: 3 },
      { name: "Redmi Note 8 Pro", memories: ["64GB", "128GB"], priority: 4 },
      { name: "Redmi Note 8T", memories: ["64GB"], priority: 5 },
      {
        name: "Redmi Note 8",
        memories: ["32GB", "64GB", "128GB"],
        priority: 6,
      },
      { name: "Redmi 9", memories: ["32GB", "64GB"], priority: 7 },
      { name: "Redmi 9C", memories: ["32GB", "64GB"], priority: 8 },
      { name: "Redmi 9A", memories: ["32GB"], priority: 9 },
      { name: "Redmi 8", memories: ["64GB"], priority: 10 },
      { name: "Redmi 8A", memories: ["64GB"], priority: 11 },
    ],
  },
  {
    deviceOs: "android",
    name: "Motorola One",
    manufacturer: "Motorola",
    priority: 9,
    models: [
      { name: "Motorola One Fusion+", memories: ["128GB"], priority: 1 },
      { name: "Motorola One Fusion", memories: ["128GB", "64GB"], priority: 2 },
      { name: "Motorola One Zoom", memories: ["128GB"], priority: 3 },
      { name: "Motorola One Vision", memories: ["128GB"], priority: 4 },
      { name: "Motorola One Hyper", memories: ["128GB"], priority: 5 },
      { name: "Motorola One", memories: ["64GB"], priority: 6 },
      { name: "Motorola One Action", memories: ["128GB"], priority: 7 },
      { name: "Motorola One Macro", memories: ["64GB"], priority: 8 },
    ],
  },
  {
    deviceOs: "android",
    name: "Motorola Edge",
    manufacturer: "Motorola",
    priority: 10,
    models: [
      { name: "Motorola Edge Plus", memories: ["256GB"], priority: 1 },
      { name: "Motorola Edge", memories: ["128GB"], priority: 2 },
    ],
  },
  {
    deviceOs: "android",
    name: "Motorola Moto G",
    manufacturer: "Motorola",
    priority: 11,
    models: [
      { name: "Moto G9 Plus", memories: ["128GB"], priority: 1 },
      { name: "Moto G9 Play", memories: ["64GB"], priority: 2 },
      { name: "Moto G8 Power Lite", memories: ["64GB"], priority: 3 },
      { name: "Moto G8 Power", memories: ["64GB"], priority: 4 },
      { name: "Moto G8", memories: ["64GB"], priority: 5 },
      { name: "Moto G8 Plus", memories: ["64GB"], priority: 6 },
      { name: "Moto G8 Play", memories: ["32GB"], priority: 7 },
    ],
  },
];

export default smartphoneModels;
