FROM node:12.16.3-alpine

RUN apk update && apk add \
    build-base python2 git libpq postgresql-dev libc-dev \
    gcc g++ linux-headers postgresql-client openssh bash

WORKDIR /app

COPY yarn.lock .
COPY package.json .
RUN yarn install

COPY . .
